### ISSUE TITLE
Is the schedule job survive after blackout?

### ISSUE THREAD

**Issue by elcolie** [rq/rq-scheduler#165]
This is a very noob question.
Is the schedule job survive after my server blackout?
From my understanding. It will persist and will continue run if that job is not triggered.

I use `Redis` on the Docker ecosystem and let it store the data on physical volume
```
redis:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
  - ./data:/data
```
**Reference:**
https://stackoverflow.com/questions/35022883/why-cant-redis-access-the-disk-in-docker-compose
